name: gtfree-ser
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - numpy>=2.1
  - scipy>=1.13
  - scikit-learn>=1.5
  - pandas>=2.2
  - matplotlib
  - pysoundfile
  - libsndfile
  - ipykernel
  - tqdm
  - lightning>=2.4
  - tensorboardx
  - regex
  - pyyaml
  - typing_extensions
  - llvm-openmp
  - openssl
  - ca-certificates
  - certifi

  - pip:
      - torch>=2.5
      - torchaudio>=2.5
      - transformers==4.46.1
      - tokenizers==0.20.3
      - huggingface-hub==0.33.4
      - einops==0.8.1
      - librosa==0.11.0
      - pyloudnorm==0.1.1
      - soxr==0.5.0.post1
      - umap-learn==0.5.9.post2
      - sentencepiece==0.2.0
      - openai==1.97.1
      - google-genai==1.27.0
      - azure-cognitiveservices-speech==1.45.0
      - funasr==1.2.6
      - modelscope==1.28.1